FROM python:3.14-slim

WORKDIR /app

COPY pyproject.toml ./

RUN pip install --no-cache-dir typer pytest

COPY src/ ./src/

COPY tests/ ./tests/

ENV PYTHONPATH=/app

CMD ["pytest", "tests/test.py", "-v"]